weather:
    resource: "@WeatherBundle/Resources/config/routing.yml"
    prefix:   /api    
    
index:
    path: /
    defaults:
        _controller: AppBundle:Default:index
        template: web/bundles/index.html